### 书稿中的代码是在TF1.0版本下，现在主流平台已更新到TF2.0，因此代码有微调

In [1]:
#代码示例：8-1
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
X=tf.constant(
    [
        [
            [[3],[-1],[3]],
            [[9],[2],[4]],
            [[8],[1],[5]]
        ]
    ]
    ,tf.float32
)
K=tf.constant(
    [
        [
            [[5]],[[2]]],
        [
            [[1]],[[3]]
        ]
    ]
    ,tf.float32
)
# same卷积
conv=tf.nn.conv2d(X,K,(1,1,1,1),'SAME')
session=tf.compat.v1.Session()
print(session.run(conv))

[[[[28.]
   [15.]
   [19.]]

  [[60.]
   [34.]
   [25.]]

  [[42.]
   [15.]
   [25.]]]]


In [7]:
#代码示例：8-2
import tensorflow as tf
X=tf.constant(
    [
        [
            [[3],[-1],[3]],
            [[9],[2],[4]],
            [[8],[1],[5]]
        ]
    ]
    ,tf.float32
)
K=tf.constant(
    [
        [
            [[5]],[[2]]],
        [
            [[1]],[[3]]
        ]
    ]
    ,tf.float32
)
# valid卷积
conv=tf.nn.conv2d(X,K,(1,1,1,1),'VALID')
session=tf.compat.v1.Session()
print(session.run(conv))

[[[[28.]
   [15.]]

  [[60.]
   [34.]]]]


In [8]:
#代码示例：8-3
import tensorflow as tf
X=tf.constant(
    [
        [
            [[3,1],[-1,4],[3,2]],
            [[9,7],[2,-1],[4,3]],
            [[8,-2,],[1,5],[5,9]]
        ]
    ]
    ,tf.float32
)
K=tf.constant(
    [
        [
            [[5],[2]],[[2],[1]]],
        [
            [[1],[6]],[[3],[-4]]
        ]
    ]
    ,tf.float32
)
# valid卷积
conv=tf.nn.conv2d(X,K,(1,1,1,1),'VALID')
session=tf.compat.v1.Session()
print(session.run(conv))

[[[[80.]
   [ 7.]]

  [[41.]
   [29.]]]]


In [9]:
#代码示例：8-4
import tensorflow as tf
X=tf.constant(
    [
        [
            [[3,1],[-1,4],[3,2]],
            [[9,7],[2,-1],[4,3]],
            [[8,-2,],[1,5],[5,9]]
        ]
    ]
    ,tf.float32
)
K=tf.constant(
    [
        [
            [[5,-1,2],[2,-2,1]],[[2,2,-7],[1,5,1]]],
        [
            [[1,3,8],[6,8,2]],[[3,4,3],[-4,3,-2]]
        ]
    ]
    ,tf.float32
)
# valid卷积
conv=tf.nn.conv2d(X,K,(1,1,1,1),'VALID')
session=tf.compat.v1.Session()
print(session.run(conv))

[[[[ 80. 101. 112.]
   [  7.  32.   3.]]

  [[ 41.   3.  63.]
   [ 29. 113.  -7.]]]]


In [10]:
#代码示例：8-5
import tensorflow as tf

X=tf.constant(
    [
        [
            [[3,1],[-1,4],[3,2]],
            [[9,7],[2,-1],[4,3]],
            [[8,-2,],[1,5],[5,9]]
        ],
         [
            [[1,2],[1,2],[2,-2]],
            [[-3,4],[2,-3],[2,1]],
            [[5,-1],[3,1],[5,3]]
         ]
    ]
    ,tf.float32
)

K=tf.constant(
    [
        [
            [[5,-1,2],[2,-2,1]],[[2,2,-7],[1,5,1]]],
        [
            [[1,3,8],[6,8,2]],[[3,4,3],[-4,3,-2]]
        ]
    ]
    ,tf.float32
)
# valid卷积
conv=tf.nn.conv2d(X,K,(1,1,1,1),'VALID')
session=tf.compat.v1.Session()
print(session.run(conv))

[[[[ 80. 101. 112.]
   [  7.  32.   3.]]

  [[ 41.   3.  63.]
   [ 29. 113.  -7.]]]


 [[[ 52.  29.  -5.]
   [ -3. -18.   2.]]

  [[ -2.   6.  26.]
   [ 21.  59.  23.]]]]


In [11]:
#代码示例：8-6
import tensorflow as tf
X=tf.constant(
    [
        [
            [[3,1],[-1,4],[3,2]],
            [[9,7],[2,-1],[4,3]],
            [[8,-2,],[1,5],[5,9]]
        ]
    ]
    ,tf.float32
)
K=tf.constant(
    [
        [
            [[5],[2]],
            [[2],[1]]],
        [   
            [[1],[6]],
            [[3],[-4]]]
    ]
    ,tf.float32
)
# valid卷积
conv=tf.nn.depthwise_conv2d(X,K,(1,1,1,1),'VALID')
session=tf.compat.v1.Session()
print(session.run(conv))

[[[[ 28.  52.]
   [ 15.  -8.]]

  [[ 60. -19.]
   [ 34.  -5.]]]]


In [12]:
#代码示例：8-7
import tensorflow as tf
X=tf.constant(
    [
        [
            [[3,1],[-1,4],[3,2]],
            [[9,7],[2,-1],[4,3]],
            [[8,-2,],[1,5],[5,9]]
        ]
    ]
    ,tf.float32
)
K=tf.constant(
    [
        [
            [[5,-1,2],
             [2,-2,1]],
            [[2,2,-7],
             [1,5,1]]
        ],
        [
            [[1,3,8],
             [6,8,2]],
            [[3,4,3],
             [-4,3,-2]]
        ]
    ]
    ,tf.float32
)
# valid卷积
conv=tf.nn.depthwise_conv2d(X,K,(1,1,1,1),'VALID')
session=tf.compat.v1.Session()
print(session.run(conv))

[[[[ 28.  30.  91.  52.  71.  21.]
   [ 15.  29.   5.  -8.   3.  -2.]]

  [[ 60.  23.  71. -19. -20.  -8.]
   [ 34.  29.  -1.  -5.  84.  -6.]]]]


In [13]:
#代码示例：8-8
import tensorflow as tf
X=tf.constant(
     [
         [
             [[3],[2],[1],[4]],
             [[8],[1],[5],[9]],
             [[6],[2],[-1],[7]],
             [[-3],[4],[6],[5]]
         ]
     ]
     ,tf.float32)
# same最大值池化
maxPool=tf.nn.max_pool(X,(1,2,3,1),[1,1,1,1],'SAME')
session=tf.compat.v1.Session()
print(session.run(conv))

[[[[ 28.  30.  91.  52.  71.  21.]
   [ 15.  29.   5.  -8.   3.  -2.]]

  [[ 60.  23.  71. -19. -20.  -8.]
   [ 34.  29.  -1.  -5.  84.  -6.]]]]


In [14]:
#代码示例：8-9
import tensorflow as tf
X=tf.constant(
     [
         [
             [[3,1],[-1,4],[3,2]],
             [[9,7],[2,-1],[4,3]],
             [[8,-2],[1,5],[5,9]]
         ]
     ]
     ,tf.float32)

# 多深度张量的same池化，2行2列2深度的邻域掩码
maxPool=tf.nn.max_pool(X,(1,2,2,1),[1,2,2,1],'SAME')
session=tf.compat.v1.Session()
print(session.run(conv))

[[[[ 28.  30.  91.  52.  71.  21.]
   [ 15.  29.   5.  -8.   3.  -2.]]

  [[ 60.  23.  71. -19. -20.  -8.]
   [ 34.  29.  -1.  -5.  84.  -6.]]]]


In [15]:
#代码示例：8-10
import tensorflow as tf
X=tf.constant(
     [
        [
             [[2,5],[3,3],[8,2]],
             [[6,1],[1,2],[5,4]],
             [[7,9],[2,-3],[-1,3]]
         ],
         [
             [[3,1],[-1,4],[3,2]],
             [[9,7],[2,-1],[4,3]],
             [[8,-2],[1,5],[5,9]]
         ]
     ]
     ,tf.float32)
# 多个三维张量的same最大值池化，2行2列2深度的邻域掩码
maxPool=tf.nn.max_pool(X,(1,2,2,1),[1,2,2,1],'SAME')
session=tf.compat.v1.Session()
print(session.run(conv))

[[[[ 28.  30.  91.  52.  71.  21.]
   [ 15.  29.   5.  -8.   3.  -2.]]

  [[ 60.  23.  71. -19. -20.  -8.]
   [ 34.  29.  -1.  -5.  84.  -6.]]]]


In [16]:
#代码示例：8-11
import tensorflow as tf
X=tf.constant(
     [
         [
             [[3,1],[-1,4],[3,2]],
             [[9,7],[2,-1],[4,3]],
             [[8,-2],[1,5],[5,9]]
         ]
     ]
     ,tf.float32)
# same平均值池化，2行2列2深度的邻域掩码
avgPool=tf.nn.avg_pool(X,(1,2,2,1),[1,2,2,1],'SAME')
session=tf.compat.v1.Session()
print(session.run(conv))

[[[[ 28.  30.  91.  52.  71.  21.]
   [ 15.  29.   5.  -8.   3.  -2.]]

  [[ 60.  23.  71. -19. -20.  -8.]
   [ 34.  29.  -1.  -5.  84.  -6.]]]]


In [17]:
#代码示例8-12
import tensorflow as tf
X=tf.constant(
     [
         [
             [[3],[2],[1],[4]],
             [[8],[1],[5],[9]],
             [[6],[2],[-1],[7]],
             [[-3],[4],[6],[5]]
         ]
     ]
     ,tf.float32)
# valid最大值池化
maxPool=tf.nn.max_pool(X,(1,2,2,1),[1,1,1,1],'VALID')
session=tf.compat.v1.Session()
print(session.run(conv))

[[[[ 28.  30.  91.  52.  71.  21.]
   [ 15.  29.   5.  -8.   3.  -2.]]

  [[ 60.  23.  71. -19. -20.  -8.]
   [ 34.  29.  -1.  -5.  84.  -6.]]]]


In [18]:
#代码示例8-13
import tensorflow as tf
X=tf.constant(
     [
         [
             [[3,1],[-1,4],[3,2]],
             [[9,7],[2,-1],[4,3]],
             [[8,-2],[1,5],[5,9]]
         ]
     ]
     ,tf.float32)
# 多深度张量的valid池化
maxPool=tf.nn.max_pool(X,(1,2,2,1),[1,1,1,1],'VALID')
session=tf.compat.v1.Session()
print(session.run(conv))

[[[[ 28.  30.  91.  52.  71.  21.]
   [ 15.  29.   5.  -8.   3.  -2.]]

  [[ 60.  23.  71. -19. -20.  -8.]
   [ 34.  29.  -1.  -5.  84.  -6.]]]]


In [19]:
#代码示例8-14
import tensorflow as tf
X=tf.constant(
     [
         [
             [[3,1],[-1,4],[3,2]],
             [[9,7],[2,-1],[4,3]],
             [[8,-2],[1,5],[5,9]]
         ],
        [
             [[1,4],[9,3],[1,1]],
             [[1,1],[1,2],[3,3]],
             [[2,1],[3,6],[4,2]]
         ]

     ]
     ,tf.float32)
# 多个三维张量的valid池化
maxPool=tf.nn.max_pool(X,(1,2,2,1),[1,1,1,1],'VALID')
session=tf.compat.v1.Session()
print(session.run(conv))

[[[[ 28.  30.  91.  52.  71.  21.]
   [ 15.  29.   5.  -8.   3.  -2.]]

  [[ 60.  23.  71. -19. -20.  -8.]
   [ 34.  29.  -1.  -5.  84.  -6.]]]]
